Add files via upload
Vacheprime/SystemMonitor pull request #3
Opened 2024-11-13 17:12 UTC by Asumakn

m m

2024-11-20 02:27 UTC, Asumakn commented
m

2024-11-20 15:30 UTC, Vacheprime requested changes
The overall functionality looks good. However, the input validation is missing.

For the add user, the username and password should be validated in order to make sure that they are not empty (maybe the password can be left empty, but not the username). Also, consider using `sudo useradd -p "$password" "$name"` instead of `sudo useradd -p $password $name` so that if the username or passwords contain a space, the command does not interpret the input as two distinct arguments.

For the give root permission, adding the user to the `root` group does not give him root permissions. Instead, it allows the user to read, write, or execute files which are a part of the `root` group and only if the appropriate permission is given to that group. I tried to create a file in one of the root directories and was unable to do so because the `root` group did not have write permission on that folder.

As for the show users, make sure to not display duplicate users. On my side, when I ran the command, it shows my own user twice.

For the other commands, validate the input.

2024-11-30 17:38 UTC, Vacheprime requested changes
Some of the input validation works as expected, but some of it does not. 
For the give root permission, it does not check if the user specified exists before giving him root privileges. Also, it would be good to indicate that the root privileges are given via sudo. 

In one of your commits, you accidentally deleted the show groups task.

Finally, polish the output of the commands so it is more user friendly. For example, when the password has been incorrectly retyped (for the add user task), there is a lot of error messages from both passwd and from your output.

2024-12-04 03:27 UTC, florencekn approved these changes

2024-12-04 07:56 UTC, merged