Luke network
Vacheprime/SystemMonitor pull request #4
Opened 2024-11-13 17:24 UTC by Asumakn

Added network file

2024-11-20 15:34 UTC, Vacheprime commented on Network.sh
> +echo "select an opiton"
Typo for option.

2024-11-20 15:48 UTC, Vacheprime commented on Network.sh
> +                nmcli dev wifi connect $netName  password $pass
Consider using `"$netName"` and "$pass" so that the parameters are enclosed in double quotes, and are not mistaken for two distinct arguments.

2024-11-20 16:01 UTC, Vacheprime requested changes
All of the commands seem to work except for the show list command.

The show list lists the interfaces and IP addresses, but it does not display the default gateway. It also displays additional information which could be removed if you desire so.

For the enable and disable card commands, the application does not indicate a success or error message after it completes. There is no output.

When you are displaying the list of networks that you can connect to, you are first storing the list of networks into a file and then using the `uniq -u` command to show only the unique lines. However, although it does print out the the network names, it still shows duplicate names. You should instead run `nmcli dev wifi | awk '{print $2}' | sort | uniq` to display only unique lines. Before using the `uniq` command, the lines must first be sorted because `uniq` only checks adjacent lines. This also removes the need to create a file. 

In general, add user input validation.

Finally, remove the duplicate `Network.sh` file located at the root of the project.

2024-11-30 17:17 UTC, Vacheprime approved these changes
Good work adding input validation. 
Like I mentioned in class, please try to polish the output (punctuation, capital letters), maybe add more detailed messages as for which input specifically is invalid.

The show list command still does not display the default gateway.

Approving the pull request so we can start merging some code into the main application.

2024-12-04 03:28 UTC, florencekn approved these changes

2024-12-04 03:32 UTC, merged